- src/config/user-setting.json
- src/elements/ts-main/ts-dashboard.html
- src/elements/ts-settings/ts-settings.html
Now the prompted link after uploaded will be: **_read.bibletranslationtools.org..._**
e.g. `http://read.bibletranslationtools.org/u/clash/bn_mat_text_ulb/`
instead of
> Change Upload Success Link

- src/js/lib/utils.js
Added default locations to retrieve fonts in different OS
_Tested on windows build and docker with mounted volume to one of the default fonts directories_
> Look for User Installed Fonts

- src/config/defaults.json
- src/js/user.js
replace "ts-desktop" with "btt-writer-desktop"
> Change Gitea Repo Token

- src/elements/ts-dialogs/ts-loading.html
- src/js/user.js
**Replace gogs client api call** 
` listRepo() `
**with** 
` searchRepo(..., limit) ` where limit = 1000 (a large offset number)
since the former may return no more than 30 results.
_Note: this is a temporary fix until the gogs client api supports paging for searchRepo()_
> Fix: Upload failed when a user has so many repos

- src/js/lib/utils.js
Added possible user font directory for macOS
> User Installed Font (macOS)

- src/elements/ts-translate/ts-resource/ts-resource-display.html
- src/elements/ts-translate/ts-translate.html
- src/js/database.js
- src/js/projects.js
This PR refactors the translationWords code to pass the current source text language down to the loading functions.  This allows BW to show translationWords content for languages other than English.
> Remove English restriction for translationWords

- src/assets/LICENSE.md
- src/elements/ts-legal/ts-guidelines.html
- src/elements/ts-legal/ts-license.html
- src/elements/ts-legal/ts-software.html
- src/elements/ts-legal/ts-statement.html
- Statement of Faith
- License Agreement
- Translation Guidelines
> Update license & terms

- src/elements/ts-translate/ts-translate.html
- src/js/projects.js
TW projects seems not having source translations and should default to English instead
> Fix: Creating translationWords project error

- src/js/lib/utils.js
Resolves issue #8 
Look for fonts in sub directories of defined directories.
> Load fonts from subdirectories

- src/css/print.css
- src/elements/ts-dialogs/ts-print-options.html
- src/elements/ts-main/ts-dashboard.html
- src/elements/ts-print/ts-print.html
- src/js/printer.js
- src/js/render.js
> Adds Language and Resource names to the pdf title

- .gitignore
- src/js/main.js
> Fixed bug when canceling import led to crash

- src/elements/ts-profile/ts-login-option.html
> redirect user to account creation on login screen

- scripts/win_installer.iss
- win64_installer.iss
> Change software URL endpoint

- i18n/en.json
- src/elements/ts-profile/ts-login-option.html
Pressing Enter will submit the login form
> Allow login with Enter key

- src/js/render.js
Removes link (href) to avoid crashing the app on click
> Remove href from resource html

- src/elements/ts-translate/ts-translate-sidebar.html
This PR prevents navigating to a negative or zero chapter either by clicking the "prev" button or entering the value
> Fix chapter navigation

- src/elements/ts-legal/ts-statement.html
Remove "essential beliefs" phrase - requested by @ChrisJarka
> Update Statement of Faith

- Dockerfile
- gulpfile.js
- package.json
Bump electron and node version
> Upgrade electron 21.3.0

- package.json
> Update archiver lib to the latest version to fix empty manifest bug

- src/js/gitnative.js
Fixes branch name issue on Mac's
> add specific master branch

- src/config/user-setting.json
Fixes #132.
- Set default reader url schema to https
> Change default reader url schema to https

- src/js/main.js
Fixes # .
- Prevent the app to open multiple instances.
> Allow only one instance of the app

- src/elements/ts-translate/ts-source/ts-source-tab.html
Fixes #137  .
- Hide "add source" button when limit (3 items) reached.
- Add ability to remove sources from tabs.
> Hide "add source" button when limit reached.

- src/js/render.js
Fixes #120 .
- Add support for paragraph markers
> Render paragraph markers (\p) as paragraphs in output text

- src/css/main.css
- src/elements/ts-main/app-theme.html
- src/elements/ts-new/ts-new.html
- src/elements/ts-translate/ts-target/ts-target-conflict.html
Fixes #123, #141.
- Fixed merge conflict colors in dark mode
- Fixed default color for links in dark mode
> Fixed some dark mode issues

- src/elements/ts-main/ts-dashboard.html
- src/js/exporter.js
Fixes #143  .
- Automatically backup project before deletion
> Backup projects before deletion

- src/elements/ts-dialogs/ts-update-options.html
- src/elements/ts-main/ts-dashboard.html
- src/js/bootstrap.js
- src/js/database.js
Fixes #157  .
- Allow to update index.sqlite to speed up getting list of available sources.
> Showing progress on index.sqlite update

- Dockerfile
- package.json
- Fix a few permissions
- Update version
> 1.3.1 Release prep

- .gitignore
- src/config/user-setting.json
- src/elements/ts-main/ts-dashboard.html
- src/elements/ts-settings/ts-settings.html
- src/js/database.js
Fixes #167.
- Add an option in settings menu to change index.sqlite url
> Allow to update index.sqlite url in settings

- src/elements/ts-main/ts-dashboard.html
- src/elements/ts-translate/ts-translate-sidebar.html
- src/elements/ts-translate/ts-translate.html
Fixes #169.
- Allow to mark all chunks of a project as done
> Allow to mark all chunks as done from menu

- src/js/lib/utils.js
Fixes # .
- Adds the path to i18n directory for MacOS builds
> Added i18n path for MacOS builds

- src/config/user-setting.json
- src/elements/ts-main/ts-dashboard.html
- src/elements/ts-settings/ts-setting-modal.html
- src/elements/ts-settings/ts-settings.html
- src/js/lib/utils.js
Fixes # .
- Use the proper way to find localization files cross-platform
> Get app root directory to find localization files

- src/elements/ts-settings/ts-settings.html
Fixes #200 .
- The app is restarted when the server suite is changed in settings.
> Restart the app when the server suite is changed

- .github/scripts/build.sh
- .github/workflows/main.yml
- gulpfile.js
- package.json
- src/js/prince-packager.js
Fixes # .
- Updated wine installation step in workflow to build Windows artifacts
> removed patch; gogs client update

- package.json
- src/js/main.js
- src/js/user.js
> Add user agent

- i18n/en.json
- src/elements/ts-translate/ts-target/ts-target-edit.html
- src/elements/ts-translate/ts-target/ts-target-note-marker.html
- src/elements/ts-translate/ts-target/ts-target-review.html
- src/elements/ts-translate/ts-target/ts-target-view.html
- src/elements/ts-translate/ts-translate.html
- src/js/render.js
Fixes #208 and #209.
- Footnote editor
> Added footnote editor

- src/js/main.js
- src/js/user.js
Fixes # .
- Use 'btt-writer-desktop' user agent in requests
> Use 'btt-writer-desktop' user agent in requests

- src/js/render.js
Fixes # .
- Fixes bug when windows-like line breaks are not rendered correctly
> use universal regex for line breaks
